### ISSUE TITLE
joequake cant launch into game (missing flame0)

### ISSUE THREAD

**Issue by lavenderdotpet** [matthewearl/JoeQuake-1#1]
![image](https://github.com/matthewearl/JoeQuake-1/assets/51702517/ba1b0363-423a-4e29-9c3d-11ccf403abd2)

issue is quake doesnt have a flame0.mdl it has flame.mdl

**Comment by lavenderdotpet** [comment]
also isnt an issue of what progs.dat r used 
same issue happens in librequake and standard quakes progs.dat

**Comment by matthewearl** [comment]
Hello, thanks for trying out this SDL port.  It looks like `flame0` is a dummy model that replaces the stock flame models with particle flames (`gl_part_flames`) is enabled.  The mdl itself is included in the quake-light package available from the [SDA downloads page](https://quake.speeddemosarchive.com/quake/downloads.html).  I think this probably affects the windows version of JQ too, in which case it might be best to raise this on [the parent repo](https://github.com/j0zzz/JoeQuake).  I regularly sync the sdl-linux branch with this repo so any fixes there should find their way here too. CC @j0zzz

**Comment by j0zzz** [comment]
If you download an official joequake release, it contains a pak0.pak that has this missing mdl file.
You can download the latest version from here:
https://github.com/j0zzz/JoeQuake/releases/tag/v0.17.7

Just extract the zip contents to your Quake folder. After you have done this, you can overwrite the joequake*.exe files with your newly compiled ones from Matt's fork.

**Comment by lavenderdotpet** [comment]
why not just set flame.mdl as a fallback or just use flame.mdl 
since this means if you run a tc  example librequake it's gonna use the joequake flame over the tc one

**Comment by j0zzz** [comment]
No, it's just an additional model file, it has a different name, **flame0.mdl**. It won't replace/hide the existing flame.mdl from the original pak0.pak from the id1 folder. This additional model file is only used by joequake, if QMB style torches are drawn. You only received that error because joequake tries to load it at startup without any condition.

**Comment by lavenderdotpet** [comment]
oh heard
